/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	AccountType: "enum",
	RenameFileInput:{
		src:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		dst:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	RFC3339Date: "String",
	Decimal: "String",
	ProjectsSortInput:{
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		owner:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		public:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		team:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Role: "enum",
	ProjectOps:{
		removeSources:{
			files:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		renameSources:{
			files:{
				type:"RenameFileInput",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		update:{
			in:{
				type:"UpdateProject",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Query:{
		checkoutData:{
			data:{
				type:"CheckoutDataInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		fileServerCredentials:{
			project:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		findProjects:{
			query:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			last:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		findProjectsByTag:{
			tag:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			last:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		getNamespace:{
			slug:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		getProject:{
			project:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		getTeam:{
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		getUser:{
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		listProjects:{
			owned:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"ProjectsSortInput",
				array:true,
				arrayRequired:false,
				required:false
			}
		},
		myTeams:{
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		predictCheckout:{
			data:{
				type:"PredictCheckoutInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	Team:{
		member:{
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		members:{
			last:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	CustomerInput:{
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		country:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		postCode:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		marketingConsent:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	NewSource:{
		filename:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		contentLength:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		contentType:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		checksum:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PredictCheckoutInput:{
		quantity:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		coupon:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		planID:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	TeamOps:{
		addMember:{
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			role:{
				type:"Role",
				array:false,
				arrayRequired:false,
				required:true
			},
			loginCallback:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createProject:{
			public:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		member:{
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		members:{
			last:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		project:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	VatInput:{
		state:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		country:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		postCode:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		number:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		companyName:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		street:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		city:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PaymentDate: "String",
	Namespace:{
		project:{
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		projects:{
			last:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	MemberOps:{
		update:{
			role:{
				type:"Role",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	SortOrder: "enum",
	Project:{
		sources:{
			last:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	ChangeSubscriptionInput:{
		subscriptionID:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:true
		},
		subscriptionPlanID:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	FileServerCredentials: "String",
	Mutation:{
		changeSubscription:{
			in:{
				type:"ChangeSubscriptionInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createProject:{
			public:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createTeam:{
			namespace:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createUser:{
			namespace:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			public:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		deployToFaker:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		removeProject:{
			project:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		sync:{
			source:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			},
			target:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		team:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateProject:{
			in:{
				type:"UpdateProject",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateSources:{
			project:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			},
			sources:{
				type:"NewSource",
				array:true,
				arrayRequired:false,
				required:true
			}
		}
	},
	CheckoutDataInput:{
		customer:{
			type:"CustomerInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		vat:{
			type:"VatInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		coupon:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		successURL:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		cancelURL:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		planID:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		quantity:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateProject:{
		project:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		public:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	Payment:{
		amount:"Decimal",
		currency:"String",
		date:"PaymentDate",
		receiptURL:"String",
		subscriptionID:"Int"
	},
	Endpoint:{
		uri:"String"
	},
	FakerSourceConnection:{
		pageInfo:"PageInfo",
		sources:"FakerSource"
	},
	Header:{
		key:"String",
		value:"String"
	},
	ProjectConnection:{
		pageInfo:"PageInfo",
		projects:"Project"
	},
	ProjectOps:{
		delete:"Boolean",
		deployToFaker:"Boolean",
		removeSources:"Boolean",
		renameSources:"Boolean",
		update:"Boolean"
	},
	Query:{
		checkoutData:"String",
		fileServerCredentials:"FileServerCredentials",
		findProjects:"ProjectConnection",
		findProjectsByTag:"ProjectConnection",
		getNamespace:"Namespace",
		getProject:"Project",
		getTeam:"Team",
		getUser:"User",
		listProjects:"ProjectConnection",
		myTeams:"TeamConnection",
		payments:"Payment",
		predictCheckout:"PredictCheckout"
	},
	Team:{
		id:"ID",
		member:"Member",
		members:"MemberConnection",
		name:"String",
		namespace:"Namespace",
		planID:"Int"
	},
	Member:{
		email:"String",
		role:"Role",
		username:"String"
	},
	SourceUploadInfo:{
		filename:"String",
		headers:"Header",
		putUrl:"String"
	},
	TeamOps:{
		addMember:"Member",
		createProject:"Project",
		delete:"Boolean",
		id:"ID",
		member:"MemberOps",
		members:"MemberConnection",
		name:"String",
		namespace:"Namespace",
		planID:"Int",
		project:"ProjectOps"
	},
	MemberConnection:{
		members:"Member",
		pageInfo:"PageInfo"
	},
	Namespace:{
		project:"Project",
		projects:"ProjectConnection",
		public:"Boolean",
		slug:"String"
	},
	Subscription:{
		cancelURL:"String",
		expiration:"String",
		quantity:"Int",
		seats:"UserConnection",
		status:"String",
		subscriptionID:"Int",
		subscriptionPlanID:"Int",
		updateURL:"String"
	},
	PageInfo:{
		last:"String",
		limit:"Int",
		next:"Boolean"
	},
	SubscriptionConnection:{
		pageInfo:"PageInfo",
		subscriptions:"Subscription"
	},
	TeamConnection:{
		pageInfo:"PageInfo",
		teams:"Team"
	},
	MemberOps:{
		delete:"Boolean",
		update:"Boolean"
	},
	Project:{
		createdAt:"RFC3339Date",
		description:"String",
		enabled:"Boolean",
		endpoint:"Endpoint",
		id:"ID",
		mocked:"Boolean",
		name:"String",
		owner:"User",
		public:"Boolean",
		slug:"String",
		sources:"FakerSourceConnection",
		tags:"String",
		team:"Team"
	},
	User:{
		accountType:"AccountType",
		id:"ID",
		namespace:"Namespace",
		subscriptions:"SubscriptionConnection",
		username:"String"
	},
	PredictCheckout:{
		price:"Float",
		trialDays:"Int"
	},
	Mutation:{
		changeSubscription:"Boolean",
		createProject:"Project",
		createTeam:"TeamOps",
		createUser:"User",
		deployToFaker:"Boolean",
		removeProject:"Boolean",
		sync:"Boolean",
		team:"TeamOps",
		updateProject:"Boolean",
		updateSources:"SourceUploadInfo"
	},
	UserConnection:{
		pageInfo:"PageInfo",
		users:"User"
	},
	FakerSource:{
		checksum:"String",
		contents:"String",
		filename:"String",
		getUrl:"String"
	}
}