export default {
  name: 'centaur-package',
  version: '0.0.0',
  description: 'Automatically generated by graphql-editor-cli',
  main: 'src/index.js',
  scripts: {
    start: 'stucco',
    update: 'gecli models && gecli schema && gecli typings',
  },
  author: 'GraphQL Editor Centaur Generator',
  license: 'ISC',
  devDependencies: {
    '@types/node': '^12.6.9',
    '@types/node-fetch': '^2.5.7',
    'babel-eslint': '^10.1.0',
    eslint: '^6.7.1',
    'eslint-config-prettier': '^6.7.0',
    'eslint-plugin-prettier': '^3.1.1',
    'graphql-zeus': 'latest',
    prettier: 'latest',
  },
  dependencies: {
    'node-fetch': '^2.6.0',
    'stucco-js': 'latest',
  },
};
