import deps from '@/deps.js';
const { dependencies, devDependencies } = deps;

export default {
  name: 'graphql-editor-cli-project',
  version: '0.0.0',
  description: 'Automatically generated by graphql-editor-cli',
  main: 'index.js',
  scripts: {
    start: 'gecli dev',
    build: 'tsc',
    watch: 'tsc --watch',
    update: 'gecli codegen models && gecli codegen typings && gecli schema',
  },
  author: 'GraphQL Editor Centaur Generator',
  license: 'ISC',
  devDependencies: {
    '@types/node': devDependencies['@types/node'],
    '@types/node-fetch': '^2.5.7',
    '@typescript-eslint/eslint-plugin': devDependencies['@typescript-eslint/eslint-plugin'],
    '@typescript-eslint/parser': devDependencies['@typescript-eslint/parser'],
    eslint: devDependencies['eslint'],
    'eslint-config-prettier': devDependencies['eslint-config-prettier'],
    'eslint-plugin-prettier': devDependencies['eslint-plugin-prettier'],
    'graphql-zeus': dependencies['graphql-zeus'],
    prettier: devDependencies['prettier'],
    'ts-node': devDependencies['ts-node'],
    typescript: devDependencies['typescript'],
  },
  dependencies: {
    'node-fetch': '^2.6.0',
    'stucco-js': dependencies['stucco-js'],
  },
};
