import deps from '@/deps.js';
const { dependencies, devDependencies } = deps;

export default {
  name: 'graphql-editor-cli-project',
  version: '0.0.0',
  description: 'Automatically generated by graphql-editor-cli',
  main: 'index.js',
  scripts: {
    start: 'gecli dev',
    build: 'tsc',
    watch: 'tsc --watch',
    update: 'gecli codegen models && gecli schema && gecli codegen typings',
  },
  author: 'GraphQL Editor Centaur Generator',
  license: 'ISC',
  devDependencies: {
    ...devDependencies,
  },
  dependencies: {
    ...dependencies,
  },
};
